### ISSUE TITLE
Issue when test_mvl_toolkit.py

### ISSUE THREAD

**Issue by EnriqueSolarte** [mvlchallenge/mvl_toolkit#6]
Some participants have encountered the following error when running `python test_mvl_toolkit.py` 
```
Loading mvl data scene 2t7WUuJeko7_0_room0...: 100%|██████████████████████████████████████████████████████████████████████████████████| 43/43 [00:00<00:00, 144.10it/s]
[PASSED]:       Download example_scene.zip
[PASSED]:       Unzip example_scene.zip as mvl-data
[PASSED]:       Download CKPT (Pretrained model)
[PASSED]:       Load mvl-data as a set of list Layouts
[FAILED]:       Eval list Layouts using HorizonNet
<class 'omegaconf.errors.ConfigAttributeError'>
('Missing key cuda_device\n    full_key: cuda_device\n    object_type=dict',)
Missing key cuda_device
    full_key: cuda_device
    object_type=dict
```
The primary reason for the issue you are encountering is a missing key argument in the configuration file associated with `test_mvl_toolkit.py`. Specifically, when you execute `test_mvl_toolkit.py`, the `eval_mvl_dataset.yaml` file is loaded. Unfortunately, the YAML file does not define the required cuda_device argument. This was an issue heritaged from previous versions.

This fixes the issue:
```YAML
cene_dir: None
scene_list: None
ckpt: None
cuda_device: 0 # --> missing argument

auto_loading:
  trained_models: ${rel_path:./trained_models.yaml}

runners:
  mvl:
    data_dir: ${scene_dir}
    scene_list: ${scene_list}
    batch_size: 10
    size: -1
    grid_size: 0.01 
    min_likelihood_percent: 0.000001
    padding: 20
    max_room_factor_size: 2
    num_workers: 5

model:
  ly_model: HorizonNet
  ckpt: ${ckpt}
  optimizer: Adam
  loss: weighted_L1
  min_std: 0.001
  epochs: 10
  save_every: -1
  lr: 0.00005
  lr_decay_rate: 0.90
  seed: 594277
  bn_momentum: 0
  freeze_earlier_blocks: -1
  beta1: 0.9
  weight_decay: 0.0
  no_save: True

```
